Update circle.ci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,84 +1,142 @@
 version: 2.1
 
 # orbs:
-  # ruby: circleci/ruby@0.1.2
+#   # ruby: circleci/ruby@0.1.2
+
+# jobs:
+#   build:
+#     working_directory: ~/articles_catalog
+
+#     # Primary container image where all commands run
+
+#     docker:
+#       - image: circleci/ruby:2.7.1
+#         environment:
+#           BUNDLE_JOBS: 3
+#           BUNDLE_PATH: vendor/bundle
+#           BUNDLE_RETRY: 3
+#           BUNDLER_VERSION: 2.2.5
+#           RAILS_ENV: test
+#           DB_HOST: 127.0.0.1
+#           PG_HOST: 127.0.0.1
+#           PGUSER: root
+
+#     # Service container image available at `host: localhost`
+
+#       - image: circleci/postgres:12.0
+#         environment:
+#           POSTGRES_USER: root
+#           POSTGRES_PASSWORD: password
+#           POSTGRES_DB: articles_catalog_test
+
+#     steps:
+#       - checkout
+
+#       # Restore bundle cache
+#       - restore_cache:
+#           keys:
+#             - rails-demo-{{ checksum "Gemfile.lock" }}
+#             - rails-demo-
+
+#       # Bundle install dependencies
+#       - run:
+#           name: Install dependencies
+#           command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
+
+#       - run:
+#           name: Waiting for PostgreSQL to start
+#           command: |
+#             for i in `seq 1 10`;
+#             do
+#               nc -z localhost 5432 && echo Success && exit 0
+#               echo -n .
+#               sleep 2
+#             done
+#             echo Failed waiting for Postgres && exit 1
+
+#       - run:
+#           name: Wait for DB
+#           command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
+
+#       - run: sudo apt install -y postgresql-client || true
+
+#       # Store bundle cache
+#       - save_cache:
+#           key: rails-demo-{{ checksum "Gemfile.lock" }}
+#           paths:
+#             - vendor/bundle
+
+#       - run:
+#           name: Database Setup
+#           command: |
+#             bundle exec rake db:create
+#             bundle exec rake db:structure:load
+
+#       - run:
+#           name: Parallel RSpec
+#           command: bin/rails test
+
+#       # Save artifacts
+#       - store_test_results:
+#           path: /tmp/test-results
+
 
 jobs:
   build:
     working_directory: ~/articles_catalog
-
-    # Primary container image where all commands run
-
+    parallelism: 2
     docker:
       - image: circleci/ruby:2.7.1
         environment:
-          BUNDLE_JOBS: 3
-          BUNDLE_PATH: vendor/bundle
-          BUNDLE_RETRY: 3
-          BUNDLER_VERSION: 2.2.5
           RAILS_ENV: test
-          DB_HOST: 127.0.0.1
-          PG_HOST: 127.0.0.1
-          PGUSER: root
-
-    # Service container image available at `host: localhost`
-
+          PGHOST: 127.0.0.1
+          PGUSER: postgres
       - image: circleci/postgres:12.0
         environment:
-          POSTGRES_USER: root
-          POSTGRES_PASSWORD: password
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
           POSTGRES_DB: articles_catalog_test
+          DATABASE_URL: "postgres://ubuntu@localhost:5432/articles_catalog_test"
 
     steps:
       - checkout
 
-      # Restore bundle cache
+      # Download and cache dependencies
       - restore_cache:
           keys:
-            - rails-demo-{{ checksum "Gemfile.lock" }}
-            - rails-demo-
-
-      # Bundle install dependencies
-      - run:
-          name: Install dependencies
-          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
+          - v1-dependencies-{{ checksum "Gemfile.lock" }}
+          # fallback to using the latest cache if no exact match is found
+          - v1-dependencies-
 
       - run:
-          name: Waiting for PostgreSQL to start
+          name: install dependencies
           command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
-              sleep 2
-            done
-            echo Failed waiting for Postgres && exit 1
-
-      - run:
-          name: Wait for DB
-          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
-
-      - run: sudo apt install -y postgresql-client || true
-
-      # Store bundle cache
+            bundle install --jobs=4 --retry=3 --path vendor/bundle
       - save_cache:
-          key: rails-demo-{{ checksum "Gemfile.lock" }}
           paths:
-            - vendor/bundle
+            - ./vendor/bundle
+          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
 
       - run:
-          name: Database Setup
+          name: Set up DB
           command: |
-            bundle exec rake db:create
-            bundle exec rake db:structure:load
-
+            bundle exec rake db:create db:schema:load --trace
+            bundle exec rake db:migrate
       - run:
-          name: Parallel RSpec
-          command: bin/rails test
-
-      # Save artifacts
+          name: run tests
+          command: |
+            mkdir /tmp/test-results
+            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
+            bundle exec rspec --format progress \
+                            --out /tmp/test-results/rspec.xml \
+                            --format progress \
+                            $TEST_FILES
+      # collect reports
       - store_test_results:
           path: /tmp/test-results
+      - store_artifacts:
+          path: /tmp/test-results
+          destination: test-results
 
 workflows:
   version: 2
